import type { StoredCampaign } from '../campaign/store'
import type { StoredBusiness } from '../lib/business.types'
import {
  CREATIVE_LIMITS,
  text,
  type CreativeCaptions,
  type CreativeContent,
  type CreativeCopyDraft,
} from './validate'

/**
 * Campaign → creative copy, deterministically.
 *
 * Same architecture as campaign building: the model call is an improvement,
 * not a dependency. This draft is assembled purely from campaign fields the
 * owner has already seen — key message, call to action, offer — so it can
 * never say anything the campaign does not, and creating marketing materials
 * never fails because a model was slow.
 */

export function draftCreativeCopyFromCampaign(
  campaign: StoredCampaign,
  setPosition = 0,
): {
  name: string
  content: Omit<CreativeContent, 'image' | 'layout'>
  captions: CreativeCaptions
} {
  const headline = clamp(draftHeadlineSource(campaign, setPosition), CREATIVE_LIMITS.headline)
  const cta = clamp(campaign.callToAction, CREATIVE_LIMITS.callToAction)
  const offerText = clamp(campaign.offer?.description ?? null, CREATIVE_LIMITS.offerText)

  // The caption leads with the same approved line the poster does, so a
  // sibling's copy matches its own poster rather than poster one's.
  const sentence = [
    draftHeadlineSource(campaign, setPosition),
    campaign.callToAction ? `${campaign.callToAction}.` : null,
  ]
    .filter(Boolean)
    .join(' ')
  const shortCopy = clamp(sentence || campaign.name, CREATIVE_LIMITS.shortCopy)

  return {
    name: clamp(draftName(campaign, setPosition), CREATIVE_LIMITS.name) ?? 'Campaign Poster',
    content: {
      headline,
      subheadline: null,
      body: null,
      callToAction: cta,
      offerText,
    },
    captions: {
      facebook: shortCopy,
      instagram: shortCopy,
      short: shortCopy,
      whatsapp: campaign.channels.includes('whatsapp') ? shortCopy : null,
      // Deliberately empty. A campaign sentence repeated under an "X" and a
      // "TikTok" label is not a platform variant, and this draft only ships
      // when the writer was unavailable — announced to the owner as a draft.
      // Better to say the copy isn't there than to fake it.
      x: null,
      tiktok: null,
    },
  }
}

/**
 * Which campaign field this poster leads with.
 *
 * A set of three is generated by calling this once per position, and until
 * Phase 7K every position got `keyMessage` — so when the writer was
 * unavailable (a rate limit, an exhausted balance) the owner received three
 * posters carrying the same name and the same headline. Three identical
 * drafts read as a bug, not as a choice.
 *
 * The first poster is unchanged: the key message, or the campaign name when
 * there is none. Later positions rotate onto other lines the owner has
 * already approved on the same campaign. Nothing is invented, and an offer
 * only qualifies when the business actually has it — a `recommendation`
 * offer is still EVA's advice, phrased as advice ("Consider a weekday lunch
 * set"), and belongs nowhere near a headline.
 *
 * A campaign that genuinely has only one usable line still repeats it. That
 * is honest — there is nothing else it has said — and the art direction
 * still gives the three posters three different designs.
 */
function draftHeadlineSource(campaign: StoredCampaign, setPosition: number): string | null {
  const lead = campaign.keyMessage ?? campaign.name
  const alternates = [
    campaign.offer?.basis === 'existing' ? campaign.offer.description : null,
    campaign.positioning,
    campaign.name,
  ].filter((value): value is string => Boolean(value?.trim()) && value !== lead)

  const candidates = [lead, ...alternates]
  const index = ((setPosition % candidates.length) + candidates.length) % candidates.length
  return candidates[index] ?? lead
}

/** Distinct internal labels, so a set of drafts is not three of one name. */
function draftName(campaign: StoredCampaign, setPosition: number): string {
  return setPosition > 0
    ? `${campaign.name} Poster ${setPosition + 1}`
    : `${campaign.name} Poster`
}

/**
 * Folds the fast-tier copy into the deterministic draft. Null keeps the
 * draft's value; grounding was already enforced per field in
 * `validateCreativeCopy`, so a refused (ungrounded) field falls back to
 * campaign wording here rather than shipping an invented price.
 */
export function mergeCopy(
  fallback: ReturnType<typeof draftCreativeCopyFromCampaign>,
  copy: CreativeCopyDraft,
): ReturnType<typeof draftCreativeCopyFromCampaign> {
  return {
    name: copy.name ?? fallback.name,
    content: {
      headline: copy.headline ?? fallback.content.headline,
      subheadline: copy.subheadline ?? fallback.content.subheadline,
      body: fallback.content.body,
      callToAction: copy.callToAction ?? fallback.content.callToAction,
      offerText: copy.offerText ?? fallback.content.offerText,
    },
    captions: {
      facebook: copy.facebookCaption ?? fallback.captions.facebook,
      instagram: copy.instagramCaption ?? fallback.captions.instagram,
      short: copy.shortCopy ?? fallback.captions.short,
      whatsapp: copy.whatsappCopy ?? fallback.captions.whatsapp,
      x: copy.xCopy ?? fallback.captions.x ?? null,
      tiktok: copy.tiktokCopy ?? fallback.captions.tiktok ?? null,
    },
  }
}

/**
 * Everything a creative's copy is allowed to claim: the campaign the owner
 * approved, the Business Brain's own products and prices, the business's
 * recorded contact surface — and, for edits, the owner's instruction itself.
 * A price or link that appears in none of these does not go on a poster.
 */
export function buildGroundingCorpus(params: {
  campaign: StoredCampaign
  business: StoredBusiness | null
  /** The owner's instruction, for edits — their own words are theirs to claim. */
  extra?: string[]
}): string {
  const { campaign, business } = params
  const parts: (string | null | undefined)[] = [
    campaign.name,
    campaign.objective,
    campaign.targetAudience?.description,
    campaign.offer?.description,
    campaign.positioning,
    campaign.keyMessage,
    campaign.callToAction,
    campaign.notes,
    ...campaign.assumptions,
    ...campaign.unknowns,
  ]

  if (business) {
    parts.push(business.name, business.contact.website, business.contact.whatsapp)
    for (const product of business.products) {
      parts.push(product.name, product.description)
      if (product.priceMinor !== null) {
        // Prices are stored in sen; the corpus needs them as printed: RM12.90.
        parts.push(`RM${(product.priceMinor / 100).toFixed(2)}`)
      }
    }
    const marketing = business.marketing?.value
    if (marketing) parts.push(...marketing.promotions, ...marketing.callsToAction)
  }

  parts.push(...(params.extra ?? []))
  return parts.filter(Boolean).join('\n')
}

/**
 * The corpus for a conversational edit adds two sources the initial one does
 * not have: the creative's own current copy (a price already on the poster
 * stays claimable when rewording around it) and the owner's instruction (a
 * price the owner types is theirs to use).
 */
export function buildCreativeEditCorpus(params: {
  creative: {
    name: string
    content: Omit<CreativeContent, 'image' | 'layout'> & Partial<CreativeContent>
    captions: CreativeCaptions
    ownerDirectives: string[]
  }
  campaign: StoredCampaign | null
  business: StoredBusiness | null
  instruction: string
}): string {
  const { creative } = params
  const own = [
    creative.name,
    creative.content.headline,
    creative.content.subheadline,
    creative.content.body,
    creative.content.callToAction,
    creative.content.offerText,
    creative.captions.facebook,
    creative.captions.instagram,
    creative.captions.short,
    creative.captions.whatsapp,
    creative.captions.x ?? null,
    creative.captions.tiktok ?? null,
    ...creative.ownerDirectives,
    params.instruction,
  ].filter(Boolean) as string[]

  if (params.campaign) {
    return buildGroundingCorpus({
      campaign: params.campaign,
      business: params.business,
      extra: own,
    })
  }
  return own.join('\n')
}

function clamp(value: string | null, max: number): string | null {
  return text(value, max)
}
